version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: taskmanager-db
    environment:
      MYSQL_ROOT_PASSWORD: 30042005gio
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
    restart: always